package com.saas.mapper;

import com.saas.domain.ProductType;
import org.apache.ibatis.jdbc.SQL;

public class ProductTypeSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_type
     *
     * @mbg.generated Thu Aug 01 11:10:53 CST 2019
     */
    public String insertSelective(ProductType record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("product_type");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getName() != null) {
            sql.VALUES("name", "#{name,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_type
     *
     * @mbg.generated Thu Aug 01 11:10:53 CST 2019
     */
    public String updateByPrimaryKeySelective(ProductType record) {
        SQL sql = new SQL();
        sql.UPDATE("product_type");
        
        if (record.getName() != null) {
            sql.SET("name = #{name,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }
}